name: Refresh Secrets on Server

on:
  workflow_dispatch:

jobs:
  restart-service:
    runs-on: self-hosted
    steps:
      - name: Create .env file from secret
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Restart Factotum service
        run: |
          sudo systemctl restart factotum
